package org.sscn.persistence.entities;

// Generated Aug 12, 2013 12:44:57 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * RefJabatan generated by hbm2java
 */
@Entity
@Table(name = "ref_jenis_formasi")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class RefJenisFormasi implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String nama;
	private String prefixCode;

	public RefJenisFormasi() {
		//NOOP	
	}

	public RefJenisFormasi(Integer id) {
		this.id = id;
	}

	public RefJenisFormasi(Integer id, String nama, String prefixCode) {
		this.id = id;
		this.nama = nama;
		this.prefixCode = prefixCode;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nama", length = 100)
	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}
	
	@Column(name = "prefix_code", length = 100)
	public String getPrefixCode() {
		return this.prefixCode;
	}

	public void setPrefixCode(String prefixCode) {
		this.prefixCode = prefixCode;
	}
}
