package org.sscn.persistence.entities;

// Generated Aug 14, 2013 12:27:10 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * DtPendaftaran generated by hbm2java
 */
@Entity
@Table(name = "user_peserta_temp")
public class UserPesertaTemp implements java.io.Serializable {

	private String noNik;
	private String nama;
	private int status;
	private String email;	

	public UserPesertaTemp() {
	}

	public UserPesertaTemp(String noNik, String nama, String email, int status) {
		this.noNik = noNik;
		this.nama = nama;
		this.email = email;
		this.status = status;		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "NIK", unique = true, nullable = false)
	public String getNoNik() {
		return this.noNik;
	}

	public void setNoNik(String noNik) {
		this.noNik = noNik;
	}

	@Column(name = "NAMA", nullable = false, length = 100)
	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}
	
	@Column(name = "EMAIL", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}


	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public int getStatus() {
		return this.status;
	}

}
