package org.sscn.persistence.entities;

// Generated Jul 26, 2013 12:03:44 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DtFormasi generated by hbm2java
 */
@Entity
@Table(name = "dt_formasi", catalog = "dbseleksicpns")
public class DtFormasi implements java.io.Serializable {

	private String instansi;
	private String lokasi;
	private String jabatan;
	private String pendidikan;
	private int jumlah;

	public DtFormasi() {
	}

	public DtFormasi(String instansi, String jabatan, String pendidikan,
			int jumlah) {
		this.instansi = instansi;
		this.jabatan = jabatan;
		this.pendidikan = pendidikan;
		this.jumlah = jumlah;
	}

	public DtFormasi(String instansi, String lokasi, String jabatan,
			String pendidikan, int jumlah) {
		this.instansi = instansi;
		this.lokasi = lokasi;
		this.jabatan = jabatan;
		this.pendidikan = pendidikan;
		this.jumlah = jumlah;
	}

	@Id
	@Column(name = "INSTANSI", unique = true, nullable = false, length = 4)
	public String getInstansi() {
		return this.instansi;
	}

	public void setInstansi(String instansi) {
		this.instansi = instansi;
	}

	@Column(name = "LOKASI", length = 10)
	public String getLokasi() {
		return this.lokasi;
	}

	public void setLokasi(String lokasi) {
		this.lokasi = lokasi;
	}

	@Column(name = "JABATAN", nullable = false, length = 7)
	public String getJabatan() {
		return this.jabatan;
	}

	public void setJabatan(String jabatan) {
		this.jabatan = jabatan;
	}

	@Column(name = "PENDIDIKAN", nullable = false, length = 7)
	public String getPendidikan() {
		return this.pendidikan;
	}

	public void setPendidikan(String pendidikan) {
		this.pendidikan = pendidikan;
	}

	@Column(name = "JUMLAH", nullable = false)
	public int getJumlah() {
		return this.jumlah;
	}

	public void setJumlah(int jumlah) {
		this.jumlah = jumlah;
	}

}
