package org.sscn.persistence.entities;

// Generated Jul 26, 2013 12:03:44 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DtPengumuman generated by hbm2java
 */
@Entity
@Table(name = "dt_pengumuman", catalog = "dbseleksicpns")
public class DtPengumuman implements java.io.Serializable {

	private DtPengumumanId id;

	public DtPengumuman() {
	}

	public DtPengumuman(DtPengumumanId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "instansi", column = @Column(name = "INSTANSI", nullable = false, length = 4)),
			@AttributeOverride(name = "berita", column = @Column(name = "BERITA", nullable = false, length = 100)),
			@AttributeOverride(name = "status", column = @Column(name = "STATUS", nullable = false, length = 1)) })
	public DtPengumumanId getId() {
		return this.id;
	}

	public void setId(DtPengumumanId id) {
		this.id = id;
	}

}
