package org.sscn.persistence.entities;

// Generated Jul 26, 2013 12:03:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DtUser generated by hbm2java
 */
@Entity
@Table(name = "dt_user", catalog = "dbseleksicpns")
public class DtUser implements java.io.Serializable {

	private String nip;
	private String nama;
	private String password;
	private String instansi;
	private String kewenangan;
	private Date tglCreated;
	private Date tglUpdated;
	private String nipAdmin;

	public DtUser() {
	}

	public DtUser(String nip, String nama, String password, String instansi,
			String kewenangan, Date tglCreated, Date tglUpdated, String nipAdmin) {
		this.nip = nip;
		this.nama = nama;
		this.password = password;
		this.instansi = instansi;
		this.kewenangan = kewenangan;
		this.tglCreated = tglCreated;
		this.tglUpdated = tglUpdated;
		this.nipAdmin = nipAdmin;
	}

	@Id
	@Column(name = "NIP", unique = true, nullable = false, length = 18)
	public String getNip() {
		return this.nip;
	}

	public void setNip(String nip) {
		this.nip = nip;
	}

	@Column(name = "NAMA", nullable = false, length = 100)
	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

	@Column(name = "PASSWORD", nullable = false, length = 8)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "INSTANSI", nullable = false, length = 4)
	public String getInstansi() {
		return this.instansi;
	}

	public void setInstansi(String instansi) {
		this.instansi = instansi;
	}

	@Column(name = "KEWENANGAN", nullable = false, length = 1)
	public String getKewenangan() {
		return this.kewenangan;
	}

	public void setKewenangan(String kewenangan) {
		this.kewenangan = kewenangan;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TGL_CREATED", nullable = false, length = 10)
	public Date getTglCreated() {
		return this.tglCreated;
	}

	public void setTglCreated(Date tglCreated) {
		this.tglCreated = tglCreated;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TGL_UPDATED", nullable = false, length = 10)
	public Date getTglUpdated() {
		return this.tglUpdated;
	}

	public void setTglUpdated(Date tglUpdated) {
		this.tglUpdated = tglUpdated;
	}

	@Column(name = "NIP_ADMIN", nullable = false, length = 18)
	public String getNipAdmin() {
		return this.nipAdmin;
	}

	public void setNipAdmin(String nipAdmin) {
		this.nipAdmin = nipAdmin;
	}

}
