package org.sscn.persistence.entities;

// Generated Jul 26, 2013 12:03:44 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DtPengumumanId generated by hbm2java
 */
@Embeddable
public class DtPengumumanId implements java.io.Serializable {

	private String instansi;
	private String berita;
	private String status;

	public DtPengumumanId() {
	}

	public DtPengumumanId(String instansi, String berita, String status) {
		this.instansi = instansi;
		this.berita = berita;
		this.status = status;
	}

	@Column(name = "INSTANSI", nullable = false, length = 4)
	public String getInstansi() {
		return this.instansi;
	}

	public void setInstansi(String instansi) {
		this.instansi = instansi;
	}

	@Column(name = "BERITA", nullable = false, length = 100)
	public String getBerita() {
		return this.berita;
	}

	public void setBerita(String berita) {
		this.berita = berita;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DtPengumumanId))
			return false;
		DtPengumumanId castOther = (DtPengumumanId) other;

		return ((this.getInstansi() == castOther.getInstansi()) || (this
				.getInstansi() != null && castOther.getInstansi() != null && this
				.getInstansi().equals(castOther.getInstansi())))
				&& ((this.getBerita() == castOther.getBerita()) || (this
						.getBerita() != null && castOther.getBerita() != null && this
						.getBerita().equals(castOther.getBerita())))
				&& ((this.getStatus() == castOther.getStatus()) || (this
						.getStatus() != null && castOther.getStatus() != null && this
						.getStatus().equals(castOther.getStatus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getInstansi() == null ? 0 : this.getInstansi().hashCode());
		result = 37 * result
				+ (getBerita() == null ? 0 : this.getBerita().hashCode());
		result = 37 * result
				+ (getStatus() == null ? 0 : this.getStatus().hashCode());
		return result;
	}

}
