package org.sscn.persistence.entities;

// Generated Aug 12, 2013 12:44:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * RefLokasi generated by hbm2java
 */
@Entity
@Table(name = "ref_lokasi", catalog = "dbseleksicpns")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class RefLokasi implements java.io.Serializable {

	private String kode;
	private String nama;
	private String status;
	private Set<MFormasi> MFormasis = new HashSet<MFormasi>(0);

	public RefLokasi() {
	}

	public RefLokasi(String kode) {
		this.kode = kode;
	}

	public RefLokasi(String kode, String nama, String status,
			Set<MFormasi> MFormasis) {
		this.kode = kode;
		this.nama = nama;
		this.status = status;
		this.MFormasis = MFormasis;
	}

	@Id
	@Column(name = "kode", unique = true, nullable = false, length = 10)
	public String getKode() {
		return this.kode;
	}

	public void setKode(String kode) {
		this.kode = kode;
	}

	@Column(name = "nama", length = 100)
	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

	@Column(name = "status", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLokasi")
	public Set<MFormasi> getMFormasis() {
		return this.MFormasis;
	}

	public void setMFormasis(Set<MFormasi> MFormasis) {
		this.MFormasis = MFormasis;
	}

}
